from PyQt6 import QtWidgets, QtCore, QtGui
import PyQt6

# Create calculator class with PyQt6
class Calculator(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Calculator")
        self.create_app()

    def create_app(self):
        self.grid = QtWidgets.QGridLayout()
        self.setLayout(self.grid)
        self.display = QtWidgets.QLineEdit()
        self.grid.addWidget(self.display, 0, 0, 1, 4)
        self.display.setDisabled(True)
        self.display.setAlignment(PyQt6.QtCore.Qt.AlignmentFlag.AlignRight)
        self.display.setMaxLength(15)
        self.display.setStyleSheet("background-color: #fff; color: #000; font-size: 20px; font-weight: bold;")
        self.display.setText("0")
        self.display.setReadOnly(True)
        self.display.setPlaceholderText("0")
        self.display.setClearButtonEnabled(True)
        self.display.setDragEnabled(True)
        self.display.setDragEnabled(True)
        # self.display.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.InternalMove)
        # self.display.setDragDropOverwriteMode(True)
        self.display.setDragEnabled(True)
        # self.display.setDragDropMode(PyQt6.QtWidgets.QAbstractItemView.DragDropMode.InternalMove)
        # self.display.setDragDropOverwriteMode(True)
        self.display.setDragEnabled(True)

        self.button_1 = QtWidgets.QPushButton("1")
        self.button_2 = QtWidgets.QPushButton("2")
        self.button_3 = QtWidgets.QPushButton("3")
        self.button_4 = QtWidgets.QPushButton("4")
        self.button_5 = QtWidgets.QPushButton("5")
        self.button_6 = QtWidgets.QPushButton("6")
        self.button_7 = QtWidgets.QPushButton("7")
        self.button_8 = QtWidgets.QPushButton("8")
        self.button_9 = QtWidgets.QPushButton("9")
        self.button_0 = QtWidgets.QPushButton("0")
        self.button_dot = QtWidgets.QPushButton(".")
        self.button_plus = QtWidgets.QPushButton("+")
        self.button_minus = QtWidgets.QPushButton("-")
        self.button_multiply = QtWidgets.QPushButton("*")
        self.button_divide = QtWidgets.QPushButton("/")
        self.button_equal = QtWidgets.QPushButton("=")
        self.button_clear = QtWidgets.QPushButton("C")
        self.button_clear_all = QtWidgets.QPushButton("CE")
        
        self.grid.addWidget(self.button_1, 1, 0)
        self.grid.addWidget(self.button_2, 1, 1)
        self.grid.addWidget(self.button_3, 1, 2)
        self.grid.addWidget(self.button_plus, 1, 3)
        self.grid.addWidget(self.button_4, 2, 0)
        self.grid.addWidget(self.button_5, 2, 1)
        self.grid.addWidget(self.button_6, 2, 2)
        self.grid.addWidget(self.button_minus, 2, 3)
        self.grid.addWidget(self.button_7, 3, 0)
        self.grid.addWidget(self.button_8, 3, 1)
        self.grid.addWidget(self.button_9, 3, 2)
        self.grid.addWidget(self.button_multiply, 3, 3)
        self.grid.addWidget(self.button_clear, 4, 0)
        self.grid.addWidget(self.button_0, 4, 1)
        self.grid.addWidget(self.button_clear_all, 4, 2)
        self.grid.addWidget(self.button_divide, 4, 3)
        self.grid.addWidget(self.button_dot, 5, 0)
        self.grid.addWidget(self.button_equal, 5, 1, 1, 3)
        self.show()

# Run calculator
if __name__ == "__main__":
    app = PyQt6.QtWidgets.QApplication([])
    window = Calculator()
    app.exec()